# Generated by Django 3.1.3 on 2021-01-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='content',
            field=models.CharField(max_length=200, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='image',
            field=models.ImageField(upload_to='Projects', verbose_name='Imagen'),
        ),
    ]
