# Generated by Django 3.1.3 on 2021-01-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_auto_20210126_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='content',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
